### PR TITLE
Fix error message in add command, update remnants of Phone to StudentId

### LINKED ISSUE #88: Fix the error message for Add command

### PR DESCRIPTION
**Pull request by xinnnyeee**
fixes #88

### CODE REVIEW

File: src/main/java/seedu/address/model/person/StudentId.java [hunk 1]
```diff
@@ -10,11 +10,9 @@
 public class StudentId {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Invalid command format! \n"
-                    + "edit: Edits the details of the person identified by the the student's student ID. "
-                    + "Existing values will be overwritten by the input values.\n"
-                    + "Parameters: Student ID [n/NAME] [i/STUDENT ID] [e/EMAIL ID] [c/CLASS ID] [t/TAG]...\n"
-                    + "Example: edit 1 i/91234567 e/johndoe@example.com";
+            "Invalid StudentId format! \n"
```
Comment (TasmiaH0508) [inline src/main/java/seedu/address/model/person/StudentId.java:13]: Editing the error message like this causes one of the test cases to fail. Namely, it fails the ```parse_invalidPreamble_failure()``` of EditCommandParserTest.java.

**Review by TasmiaH0508 — COMMENTED** [review]
Everything seems okay and I only have one concern, which I have raised in one review comment.

File: src/main/java/seedu/address/model/person/StudentId.java (hunk 1 above)
Comment (xinnnyeee) [reply src/main/java/seedu/address/model/person/StudentId.java:13]: It did happen to me, and I looked through the test. But I think it is acceptable for that failure to return warning given by `EditCommand.MESSAGE_USAGE`, as it is a test failure from EditCommandParseTest.java. 
Imo it is worse when the `StudentId.MESSAGE_CONSTRAINT` is set to an EditCommand error message, as the error message can be triggered whenever there's a violation in `StudentId` format, which was what happened in our Add Command smoke test.

Comment (xinnnyeee) [reply src/main/java/seedu/address/model/person/StudentId.java:13]: TLDR, I made that particular test failure expects an error message from EditCommand.MESSAGE_USAGE instead of StudentId.MESSAGE_CONSTRAINT. Essentially it still outputs the same message, just from a different source.

Comment (TasmiaH0508) [reply src/main/java/seedu/address/model/person/StudentId.java:13]: So, to be clear, out of x test cases, x - 1 of them are passing, where x is the total number of test cases currently. Did I understand that right?

Comment (xinnnyeee) [reply src/main/java/seedu/address/model/person/StudentId.java:13]: All the test cases are passing currently :)

Comment (TasmiaH0508) [reply src/main/java/seedu/address/model/person/StudentId.java:13]: In that case, I will go ahead and merge this
